/**/roboreg_stereo_local:
  ros__parameters:
    topics:
      left_image: /camera/left/image_rect_color
      left_camera_info: /camera/left/camera_info
      right_image: /camera/right/image_rect_color
      right_camera_info: /camera/right/camera_info
      depth: /camera/depth/registered
      depth_camera_info: /camera/depth/registered/camera_info
      joint_state: /joint_states
      robot_description: /robot_description

    filters:
      sync_accuracy: 0.1

    annotation:
      n_positive: 3
      n_negative: 0

    segmentation:
      device: cuda
      model_id: facebook/sam2-hiera-large
      pth: 0.5

    robot_data:
      root_link_name: ""
      end_link_name: ""
      collision_meshes: False

    tf_broadcaster:
      parent_frame: world
      child_frame: camera_frame
      target_child_frame: camera_link
