/**/roboreg_monocular_cloud:
  ros__parameters:
    topics:
      image: /camera/image_rect_color
      camera_info: /camera/camera_info
      depth: /camera/depth/registered
      depth_camera_info: /camera/depth/registered/camera_info
      joint_state: /joint_states
      robot_description: /robot_description

    filters:
      sync_accuracy: 0.1

    annotation:
      n_positive: 3
      n_negative: 0

    cloud_client:
      base_url: http://localhost:8000
      timeout: 120.0

    robot_data:
      root_link_name: ""
      end_link_name: ""
      collision_meshes: False

    tf_broadcaster:
      parent_frame: world
      child_frame: camera_frame
      target_child_frame: camera_link
