/**/roboreg_stereo_cloud:
  ros__parameters:
    topics:
      left_image:
        name: /zed/zed_node/left/image_rect_color/compressed
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
        camera_info:
          name: /zed/zed_node/left/camera_info
          qos:
            reliability: BEST_EFFORT
            durability: VOLATILE
      right_image:
        name: /zed/zed_node/right/image_rect_color/compressed
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
        camera_info:
          name: /zed/zed_node/right/camera_info
          qos:
            reliability: BEST_EFFORT
            durability: VOLATILE
      depth:
        name: /zed/zed_node/depth/depth_registered/compressedDepth
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
        camera_info:
          name: /zed/zed_node/depth/camera_info
          qos:
            reliability: BEST_EFFORT
            durability: VOLATILE
      joint_state:
        name: /lbr/joint_states
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
      robot_description:
        name: /lbr/robot_description
        qos:
          reliability: RELIABLE
          durability: TRANSIENT_LOCAL

    filters:
      sync_accuracy: 0.1

    annotation:
      n_positive: 3
      n_negative: 0

    cloud_client:
      base_url: http://localhost:8000
      timeout: 120.0

    robot_data:
      root_link_name: ""
      end_link_name: ""
      collision_meshes: False

    tf_broadcaster:
      parent_frame: world
      child_frame: zed_left_camera_frame
      target_child_frame: zed_camera_link
