<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboreg_all</name>
  <version>0.2.0</version>
  <description>Meta package for installing all other packages of roboreg ROS 2 integration.</description>
  <maintainer email="m.huber_1994@hotmail.de">mhubii</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>roboreg_idl</exec_depend>
  <exec_depend>roboreg_nodes</exec_depend>
  <exec_depend>roboreg_rviz</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>