/**/roboreg:
  ros__parameters:
    topics:
      image:
        name: /camera/image_rect_color
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
        camera_info:
          name: /camera/camera_info
          qos:
            reliability: BEST_EFFORT
            durability: VOLATILE
      depth:
        name: /camera/depth/registered
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
        camera_info:
          name: /camera/depth/registered/camera_info
          qos:
            reliability: BEST_EFFORT
            durability: VOLATILE
      joint_state:
        name: /joint_states
        qos:
          reliability: BEST_EFFORT
          durability: VOLATILE
      robot_description:
        name: /robot_description
        qos:
          reliability: RELIABLE
          durability: TRANSIENT_LOCAL

    filters:
      sync_accuracy: 0.1
      min_depth: 0.01
      max_depth: 4.0

    segmentation:
      device: cuda
      n_positive_samples: 5
      n_negative_samples: 5
      model_id: facebook/sam2-hiera-large
      pth: 0.5

    robot_model:
      device: cuda
      root_link_name: ""
      end_link_name: ""
      visual_meshes: False

    renderer:
      enabled: False
      color: "b"
      rate: 10.0

    tf_broadcaster:
      parent_frame: world
      child_frame: camera_frame
      target_child_frame: camera_link
