/**/roboreg:
  ros__parameters:
    filters:
      sync_accuracy: 1.0
      min_joint_position_change: 0.001
      max_joint_velocity: 0.01

    topics:
      image:
        name: /image_rect_color
        qos_reliability: BEST_EFFORT # loaded through getattr. From: [SYSTEM_DEFAULT, BEST_EFFORT, RELIABLE]
      camera_info:
        name: /camera_info
        qos_reliability: BEST_EFFORT
      joint_state:
        name: /joint_states
        qos_reliability: BEST_EFFORT
      point_cloud:
        name: /point_cloud/cloud_registered
        qos_reliability: BEST_EFFORT
      robot_description:
        name: /robot_description

    segmentation:
      buffer_size: 5
      model_type: vit_h
      device: cuda
      sam_checkpoint_path: ""

    registration:
      erosion_kernel_size: 10
      convex_hull: True
      number_of_points: 5000
      device: cuda
      max_distance: 0.1
      outer_max_iter: 100
      inner_max_iter: 3
      rmse_change: 1.0e-6

    tf_broadcaster:
      parent_frame: world
      child_frame: camera_frame
      target_child_frame: camera_link
