name: Rolling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: Colcon Build & Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: rolling
          colcon-defaults: |
            {
                "test": {
                    "pytest-args": [
                        "-m not linter"
                    ]
                }
            }
