name: Rolling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-resolute-latest # other tags: https://hub.docker.com/r/rostooling/setup-ros-docker/tags
    steps:
      - name: Colcon Build & Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: rolling
          colcon-defaults: |
            {
                "test": {
                    "pytest-args": [
                        "-m not linter"
                    ]
                }
            }
